"""empty message

Revision ID: 0666a33b42cf
Revises: b9b7c320390e
Create Date: 2020-06-29 19:50:59.573772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0666a33b42cf'
down_revision = 'b9b7c320390e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('existing_crid',
                    sa.Column('id', sa.Integer(), nullable=True),
                    sa.Column('existing_crids', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('existing_crid')
    # ### end Alembic commands ###
