"""Moved officer demographics to data_officer_allegation table

Revision ID: 0a56b15ae1cf
Revises: 0666a33b42cf
Create Date: 2020-07-09 17:32:56.255604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a56b15ae1cf'
down_revision = '0666a33b42cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_officerallegation', sa.Column('age', sa.String(length=50), nullable=True))
    op.add_column('data_officerallegation', sa.Column('gender', sa.String(length=1), nullable=True))
    op.add_column('data_officerallegation', sa.Column('race', sa.String(length=50), nullable=True))
    op.add_column('data_officerallegation', sa.Column('years_on_force', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_officerallegation', 'years_on_force')
    op.drop_column('data_officerallegation', 'race')
    op.drop_column('data_officerallegation', 'gender')
    op.drop_column('data_officerallegation', 'age')
    # ### end Alembic commands ###
