"""updates data_officerunknown id to be integer

Revision ID: 1fe9a81fbcb1
Revises: f94c62d406e4
Create Date: 2020-06-01 19:34:31.129156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe9a81fbcb1'
down_revision = 'f94c62d406e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_officerunknown')
    op.create_table('data_officerunknown',
                    sa.Column('id', sa.Integer(), nullable=True),
                    sa.Column('data_officerallegation_id', sa.Integer(), nullable=True),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('gender', sa.String(length=1), nullable=False),
                    sa.Column('race', sa.String(length=50), nullable=False),
                    sa.Column('years_on_force', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_officerunknown', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               autoincrement=True)
    op.alter_column('data_officerunknown', 'data_officerallegation_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
