"""changed dataofficerunknown age type from integer to string

Revision ID: 99c65ad0d581
Revises: ae6854ad2b65
Create Date: 2020-06-03 19:10:20.567371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c65ad0d581'
down_revision = 'ae6854ad2b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_officerunknown')
    op.create_table('data_officerunknown',
                    sa.Column('id', sa.Integer(), nullable=True),
                    sa.Column('data_officerallegation_id', sa.Integer(), nullable=True),
                    sa.Column('age', sa.String(length=50), nullable=True),
                    sa.Column('gender', sa.String(length=1), nullable=True),
                    sa.Column('race', sa.String(length=50), nullable=True),
                    sa.Column('years_on_force', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_officerunknown')
    op.create_table('data_officerunknown',
                    sa.Column('id', sa.Integer(), nullable=True),
                    sa.Column('data_officerallegation_id', sa.Integer(), nullable=True),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('gender', sa.String(length=1), nullable=False),
                    sa.Column('race', sa.String(length=50), nullable=False),
                    sa.Column('years_on_force', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
