"""In data_officer_unknown tables changed ids to integer type instead of string

Revision ID: ae6854ad2b65
Revises: f94c62d406e4
Create Date: 2020-06-02 18:07:48.952969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6854ad2b65'
down_revision = 'f94c62d406e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_officerunknown')
    op.create_table('data_officerunknown',
                    sa.Column('id', sa.Integer(), nullable=True),
                    sa.Column('data_officerallegation_id', sa.Integer(), nullable=True),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('gender', sa.String(length=1), nullable=False),
                    sa.Column('race', sa.String(length=50), nullable=False),
                    sa.Column('years_on_force', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_officerunknown')
    op.create_table('data_officerunknown',
                    sa.Column('id', sa.String(30), nullable=False),
                    sa.Column('data_officerallegation_id', sa.String(30), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('gender', sa.String(length=1), nullable=False),
                    sa.Column('race', sa.String(length=50), nullable=False),
                    sa.Column('years_on_force', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
