"""Initial migration.

Revision ID: c21e3b3a073f
Revises: 
Create Date: 2020-05-06 18:24:53.916304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision = 'c21e3b3a073f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_allegation',
    sa.Column('cr_id', sa.String(length=30), nullable=False),
    sa.Column('crid', sa.String(length=30), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('add1', sa.String(length=16), nullable=False),
    sa.Column('add2', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('beat_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('incident_date', sa.DateTime(), nullable=True),
    sa.Column('is_officer_complaint', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('old_complaint_address', sa.String(length=255), nullable=True),
    sa.Column('subjects', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cr_id')
    )
    op.create_table('data_officerallegation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allegation_id', sa.String(length=30), nullable=True),
    sa.Column('allegation_category_id', sa.Integer(), nullable=True),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('officer_age', sa.Integer(), nullable=True),
    sa.Column('recc_finding', sa.String(length=2), nullable=False),
    sa.Column('recc_outcome', sa.String(length=32), nullable=False),
    sa.Column('final_finding', sa.String(length=2), nullable=False),
    sa.Column('final_outcome', sa.String(length=32), nullable=False),
    sa.Column('final_outcome_class', sa.String(length=20), nullable=False),
    sa.Column('disciplined', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_officerallegation')
    op.drop_table('data_allegation')
    # ### end Alembic commands ###
